sylius_twig_hooks:
    hooks:
        'sylius_admin.payment_method.update.content.form.sections.gateway_configuration.gopay':
            form:
                template: '@ThreeBRSSyliusGoPayPlugin/admin/payment_method/form/gateway_config/gopay.html.twig'
                priority: 0
